import {
  BookOpen,
  ChartColumn,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleHelp,
  Copy,
  CornerDownRight,
  Ellipsis,
  Files,
  Filter,
  FilePlus,
  FileText,
  FolderOpen,
  Gamepad2,
  GripVertical,
  Image,
  Languages,
  Moon,
  Music,
  PanelLeft,
  Pencil,
  Play,
  Plus,
  Save,
  Search,
  Settings,
  Split,
  Sun,
  TriangleAlert,
  Trash2,
  Upload,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "book-open": BookOpen,
  "file-plus": FilePlus,
  "folder-open": FolderOpen,
  save: Save,
  "file-text": FileText,
  "gamepad-2": Gamepad2,
  play: Play,
  "circle-help": CircleHelp,
  plus: Plus,
  pencil: Pencil,
  "trash-2": Trash2,
  x: X,
  copy: Copy,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  split: Split,
  "corner-down-right": CornerDownRight,
  image: Image,
  "triangle-alert": TriangleAlert,
  search: Search,
  "grip-vertical": GripVertical,
  languages: Languages,
  "circle-alert": CircleAlert,
  "chart-column": ChartColumn,
  users: Users,
  ellipsis: Ellipsis,
  filter: Filter,
  files: Files,
  "panel-left": PanelLeft,
  sun: Sun,
  moon: Moon,
  music: Music,
  upload: Upload,
  settings: Settings,
};

export type IconName = keyof typeof ICONS;

export function Icon({ name, className }: { name: IconName; className?: string }) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp className={`lucide-icon${className ? ` ${className}` : ""}`} aria-hidden="true" />;
}
